"""adding genre to user

Revision ID: 0085105fcd92
Revises: 25cf200facff
Create Date: 2024-11-24 22:55:47.699971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0085105fcd92'
down_revision = '25cf200facff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('USR_gender', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('USR_gender')

    # ### end Alembic commands ###
