"""address settings update

Revision ID: 4646e2bec603
Revises: 
Create Date: 2024-11-11 16:19:55.035383

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4646e2bec603'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['USR_modified_by'], ['USR_userId'])
        batch_op.drop_column('USR_password_salt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('USR_password_salt', mysql.VARCHAR(length=250), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
